### ISSUE TITLE
Issue when deleting an actor

### ISSUE THREAD

**Issue by Lightningrod6** [Not-Enough-Photons/MonoDirector#22]
Whenever you delete an actor you cannot record. You can play, pause and stop but you can't record. Same goes with clearing all actors.

**Comment by adamd3v** [comment]
Duly noted. I'll get to this as soon as I can. Thank you!

**Comment by adamd3v** [comment]
This has been patched in the most recent version. I will push a release very soon, once I drop the video of course.
