### ISSUE TITLE
weapons dont work

### ISSUE THREAD

**Issue by brobloxb228** [Not-Enough-Photons/MonoDirector#23]
character just holds the magazine but gun isnt there? and i never interacted with the weapon when pressing play

**Comment by adamd3v** [comment]
You may have to propify the weapon and then record with it.

**Comment by surmix80** [comment]
I have a solution. There's a non-code mod that you can find in the releases, under the "assets" folder. It contains a spawnable object called "Propifier." You can find this in the "pallets" tab of the spawn gun, or under "MonoDirector"
So simply aim and shoot at whatever object you want your actor to interact with using the "Propifier" tool (there should be a new icon above the object for the actor to interact with), then record the action. Enjoy!
