### ISSUE TITLE
(Not a issue just a question) free cam

### ISSUE THREAD

**Issue by GoldenNuts69** [Not-Enough-Photons/MonoDirector#24]
so i got the clip i made but how do i get freecam to work, because i enabled it in the settings and i know the controls but when i play the clip i don't know how to use it when i play the clip

**Comment by GoldenNuts69** [comment]
so just wondering if i did something wrong or if im not on the right version of bonelab, like public beta or something

**Comment by adamd3v** [comment]
If I remember correctly, the "P" key is for playing stuff back. But I'm unsure if the beta version has this. The newest version **should** have keybinds for this.
