### ISSUE TITLE
The tools for monodirector dont spawn in

### ISSUE THREAD

**Issue by goat44mince4** [Not-Enough-Photons/MonoDirector#25]

**Comment by adamd3v** [comment]
Are you on Quest?

**Comment by goat44mince4** [comment]
yes

**Comment by goat44mince4** [comment]
i can see it in  the spawn gun but cant spawn it in

**Comment by goat44mince4** [comment]
@adamd3v

**Comment by adamd3v** [comment]
The assets are not compatible with Quest yet. I'll fix this very, very soon.

**Comment by goat44mince4** [comment]
yay thank you so much💙 i might create a you tube using this😀

**Comment by goat44mince4** [comment]
any idea when it will be on quest like an estimate date

**Comment by adamd3v** [comment]
Right now.

**Comment by goat44mince4** [comment]
ysysyayyayayayyayayayayayyayayayayayayyayayayayay
