### ISSUE TITLE
A lot of weird bugs

### ISSUE THREAD

**Issue by GoldenNuts69** [Not-Enough-Photons/MonoDirector#26]
so when i record it ends as soon as the timer ends to start recording, Also I don't know if I did anything wrong when putting the mods in, but I put the Spawnables in the Appdata section and the dll in melon loader mods, then put the other thing in Userdata. when I do stuff like this I most of the time mess up and can't find out what I did wrong. also the prop gun I don't know how to spell it but when I try to use it, I don't know if something is now interactable with the actor because I don't see the prop icon on the object, I'm telling this to any beta tester, dev, adamdev himself and people that don't have a problem with it to please help. **(I can make a video to show what I mean by all of this, also I don't like making issues because it sounds annoying and I bet it is)**

**Comment by CASTLETKO** [comment]
I believe the timer/recording bug has to do with using custom avatars
