### ISSUE TITLE
Custom Avatars Bug

### ISSUE THREAD

**Issue by CASTLETKO** [Not-Enough-Photons/MonoDirector#27]
Same issue found by GoldenNuts, when using a custom avatar not part of the base-game, recording will end after like 0.02 seconds. Only avatars part of the base game will actually record, as far as my knowledge.

**Comment by GoldenNuts69** [comment]
i have been trying to fix it and i can't find anything for the custom avatars, so maybe adamdev or some dev will maybe see our issues and try to fix this version, or i would need to wait for a new one to release.

**Comment by adamd3v** [comment]
This was on an older version of MonoDirector I think. I'm gonna push a new version as well right now.
