### ISSUE TITLE
How do you record? (QUESTION NOT BUG)

### ISSUE THREAD

**Issue by Brimmla** [Not-Enough-Photons/MonoDirector#29]
I haven't seen any tutorial or instructions on how to do this, so this seems to be the only place to ask.

**Comment by ShellShock72** [comment]
I want to know something similar, i know how to do most stuff but i dunno how to use the cameras, or know if they're recording, also, where the hell does it save the cameras recording?
i also can't see anything on the Gimble camera's screen.
i get this is an open beta, but theres no tutorials on this thing! your just told to 'record' and its 'as simple as that'. no, no it isnt that simple. 
i need to know how this works and where it saves recordings.

**Comment by Brimmla** [comment]
You have to enable the gimble camera in the Mono Director bonelib menu

**Comment by Brimmla** [comment]
I somehow got the freecam to work, and i don't think there's any recording in this mod. I just used OBS to make a little test

**Comment by wifhaver** [comment]
open bonemenu go to not enough photons mono director then the top one (i forgot the name) click record and do a scene or whatever you want to. after doing what you wanted to you can click stop and it will keep what you did and after that hit play and a rig of the player will do everything you did. ive seen the clones hold items but idk how to do that sadly. and if you are meaning actually recording it then use obs and edit out the parts you dont like with filmora or even clipchamp.

**Comment by ShellShock72** [comment]
> open bonemenu go to not enough photons mono director then the top one (i forgot the name) click record and do a scene or whatever you want to. after doing what you wanted to you can click stop and it will keep what you did and after that hit play and a rig of the player will do everything you did. ive seen the clones hold items but idk how to do that sadly. and if you are meaning actually recording it then use obs and edit out the parts you dont like with filmora or even clipchamp.

You can use the propify tool to make it record objects and guns and stuff.
its fun

**Comment by ShellShock72** [comment]
> You have to enable the gimble camera in the Mono Director bonelib menu

Yeah i know that, but it doesn't work, nothing appears on the screen
