### ISSUE TITLE
Limbs get stuck

### ISSUE THREAD

**Issue by androlduser** [Not-Enough-Photons/MonoDirector#40]
I've encountered this bug where if I interact with an actor during playback, my arm gets stuck into the actor and my body freezes up. Only fix i know is to delete the actor. Not 100% sure if this is a monodirector issue or a conflicting mod. Ive attached a file showing the bug happening. (It happens on other avatars too, I just wanted to use the avatars I was using before I encountered the bug to be as accurate as possible)

https://github.com/Not-Enough-Photons/MonoDirector/assets/167147307/2bed981d-29cb-4f63-904b-4915203629ab

**Comment by adamd3v** [comment]
This is a problem with grip events on avatars. I think it may be the game itself breaking since rig references break when I clone the avatar.
