### ISSUE TITLE
Issues with Caster Menu

### ISSUE THREAD

**Issue by surmix80** [Not-Enough-Photons/MonoDirector#41]
MonoDirector v1.1.1
BONELAB Beta: public_beta (Patch 3)
MelonLoader v0.5.7 Open-Beta

This is one of many posts documenting bugs related to MonoDirector. I only intend to help.

Firstly, the Caster menu doesn't show all of the actors in the scene, even if I use the arrows to switch from page to page. Secondly, the actors can't be deleted using the Caster menu or the Actors menu. Thirdly, re-casting actors leads to a softlock.
For an in-depth analysis and demonstration, there is a YouTube video linked.

https://youtu.be/obT4XYSEfXA

**Comment by adamd3v** [comment]
I have improved this in the latest release on Thunderstore. 
:)
